version: '3.1'

services:
  uniscan:
    image: uniscan:latest
    build:
      context: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_development
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - '3002:3000'
    volumes:
      - storage_data:/app/storage:ro

  uniscan_test:
    image: uniscan:latest
    build:
      context: .
    command: ["rails", "test"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_test
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - RAILS_ENV=test

  sidekiq:
    image: uniscan:latest
    build:
      context: .
    command: ["bundle", "exec", "sidekiq"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_development
      - DB_USERNAME=root
      - DB_PASSWORD=root

  fetch_collections:
    image: uniscan:latest
    build:
      context: .
    command: ["rails", "fetch_collections:fetch"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_development
      - DB_USERNAME=root
      - DB_PASSWORD=root

  fetch_tokens:
    image: uniscan:latest
    build:
      context: .
    command: ["rails", "fetch_tokens:fetch"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_development
      - DB_USERNAME=root
      - DB_PASSWORD=root

  fetch_transfers:
    image: uniscan:latest
    build:
      context: .
    command: ["rails", "fetch_transfers:fetch"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_development
      - DB_USERNAME=root
      - DB_PASSWORD=root

  token_uri:
    image: uniscan:latest
    build:
      context: .
    command: ["rails", "token_uri:parse"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_development
      - DB_USERNAME=root
      - DB_PASSWORD=root

  update_creator:
    image: uniscan:latest
    build:
      context: .
    command: ["rails", "update_creator"]
    environment:
      - DB_HOST=db
      - DB_DATABASE=uniscan_development
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - ETHERSCAN_APIKEY=CQZEXX84G6AQ5R8AZCII626EA43VPNJEEU

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uniscan_development

  redis:
    image: redis:4.0.10
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
  storage_data:
