version: '3.1'

services:
  uniscan:
    image: uniscan:latest
    build:
      context: .
    command: ["rails", "server", "-b", "0.0.0.0"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_development
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - '3000:3000'

  uniscan_test:
    image: uniscan:latest
    build:
      context: .
    command: ["rails", "test"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_test
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - RAILS_ENV=test

  sidekiq:
    image: uniscan:latest
    build:
      context: .
    command: ["bundle", "exec", "sidekiq"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_DATABASE=uniscan_development
      - DB_USERNAME=root
      - DB_PASSWORD=root

  eth_scan:
    image: uniart/evm-nft-tracker
    command: ["ethereum-nft-tracker", "12994586", "s"]
    environment:
      - REDIS_URL=redis://redis:6379


  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uniscan_development
    ports:
      - '3306:3306'

  redis:
    image: redis:4.0.10
    command: --character-set-server=utf8mb4
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
